# Generated by Django 3.0.3 on 2020-02-23 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Htmls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=246)),
                ('desc', models.CharField(max_length=700)),
                ('html', models.FileField(upload_to='uploads/')),
            ],
        ),
    ]
