# Generated by Django 3.0.3 on 2020-02-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Htmls',
            new_name='Html',
        ),
    ]
