# Generated by Django 3.0.3 on 2020-02-23 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show', '0002_auto_20200223_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='html',
            name='desc',
            field=models.CharField(blank=True, max_length=700),
        ),
    ]
